## Important Functions

In [1]:
import numpy as np

In [2]:
# Random Function
print(np.random.random()) # Changes every time you run the cell

0.1298951460812514


In [3]:
print(np.random.seed(1)) # seeds the next one accurence 
print(np.random.random()) # now the randomly generated number doesnt change

None
0.417022004702574


In [4]:
# You can generate any random values between a given range
np.random.uniform(1, 100, 10).reshape(5,2)
# generates 10 random values between 1 and 100
# yes you can reshape it further

array([[72.31212485,  1.01132311],
       [30.93092469, 15.52883319],
       [10.14152088, 19.43976093],
       [35.21051198, 40.27997995],
       [54.34285667, 42.50025693]])

In [5]:
# to generate only integers
arr = np.random.randint(1, 10, 15).reshape(3,5)
# generate 15 integers between 1 and 10 and reshape into (3,5)
print(arr)

[[3 5 3 5 8]
 [8 2 8 1 7]
 [8 7 2 1 2]]


In [6]:
# we are familiar with min and max functions
print(np.min(arr))
print(np.max(arr))

1
8


In [7]:
# to get the index of the min or max element
print(np.argmax(arr))
print(np.argmin(arr))

4
8


In [8]:
# suppose you want to replace all the odd elements with -1
arr[arr%2 != 0] = -1
print(arr)
# doing this will change the current function

[[-1 -1 -1 -1  8]
 [ 8  2  8 -1 -1]
 [ 8 -1  2 -1  2]]


In [9]:
# where functions - it is like conditional statement
a = np.random.randint(1, 50, 5)
print(a)
b = np.where(a%2 == 1, -1, a)
# this will replace all the odd elements with -1 and the rest are left as is
print(b)

[ 9 25 14 48 43]
[-1 -1 14 48 -1]


In [10]:
# percentile
c = np.random.randint(1, 50, 10)
c = np.sort(c)
print(c)
np.percentile(c, 50)
# this means that 50 percent of elements are less than this value

[ 4  4  5  7  8  9 22 25 31 44]


8.5