## Reshaping NumPy Arrays

In [2]:
import numpy as np

In [13]:
arr1 = np.arange(6).reshape(3,2)
# ravel function - does the same things like np.nditer()
# converts an N dimesional array to 1D
print(arr1)
print(arr1.ndim)
print("After Unravelling......")
arr2 = arr1.ravel()
print(arr2)
print(arr2.ndim)

[[0 1]
 [2 3]
 [4 5]]
2
After Unravelling......
[0 1 2 3 4 5]
1


In [14]:
# Transpose - self explainatory
arr1.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [21]:
# Stacking arrays
arr3 = np.arange(6, 12).reshape(3,2)
print(arr1)
print(arr3)
# Horizontally
arr4 = np.hstack((arr1, arr3))
# Vertically
arr5 = np.vstack((arr1, arr3))
print("Horizontally Stacking....")
print(arr4)
print("Vertically Stacking....")
print(arr5)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
Horizontally Stacking....
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]
Vertically Stacking....
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [28]:
# Splitting Arrays
# hsplit splits into columns...
print(np.hsplit(arr5, 2))
# vsplit splits into rows...
print(np.vsplit(arr5, 3))

[array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]]), array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]])]
[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11]])]


## Indexing Using Boolean Arrays

In [34]:
# Suppose you only want the elements which are greater then 50 from an array
print(arr4 > 4)
# now we superimpose this array on other array and make a new one only when there is true
arr6 = arr4[arr4 > 4]
print(arr6)

[[False False  True  True]
 [False False  True  True]
 [False  True  True  True]]
[ 6  7  8  9  5 10 11]


In [37]:
# the logic can be complex as well
arr7 = arr4[(arr4 > 3) & (arr4 % 2 != 0 )]
print(arr7)

[ 7  9  5 11]


In [41]:
# You can even change the elements in the original array with the same constraints
arr3[(arr3 > 5) & (arr3 % 2 == 0)] = 10
print(arr3)

[[10  7]
 [10  9]
 [10 11]]
