# Numpy Operations

In [2]:
import numpy as np

In [15]:
# Creating two numpy arrays
arr1 = np.arange(1,7)
arr2 = np.arange(4,10)
print(arr1)
print()
print(arr2)

[1 2 3 4 5 6]

[4 5 6 7 8 9]


In [10]:
# simple arithmatic functions can be directly used on objects
arr1 - arr2
# this will perform element wise substraction

array([-3, -3, -3, -3, -3, -3])

In [13]:
# Scalar Multiplication can be done as follows
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [18]:
# Vector Multiplication can also be done element wise
arr1 * arr2 # note that this NOT the DOT or CROSS Product

array([ 4, 10, 18, 28, 40, 54])

In [21]:
# Logical Statements return boolean values
arr2 > 5
# this will return an array of the some size but containing boolean values

array([False, False,  True,  True,  True,  True])

In [23]:
# DOT product
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6, 12).reshape(3,2)
arr3.dot(arr4)
# since the dimensions allow this, it will work

array([[ 28,  31],
       [100, 112]])

In [26]:
# minimum and maximum have there own small methods
print(arr3.min())
print(arr3.max())

0
5


In [28]:
# for a row wise minimum/maximum we can enter a paramater called 'axis'
print(arr4.min(axis=0))
print(arr4.max(axis=0))
# for column wise min/max the axis should be given as 1
print(arr4.min(axis=1))
print(arr4.max(axis=1))

[6 7]
[10 11]
[ 6  8 10]
[ 7  9 11]


In [34]:
# calculate the sum of all the elements
print(arr3.sum())

# row/column wise sum can be returned using the same 'axis'
print(arr3.sum(axis=0)) # for rows
print(arr3.sum(axis=1)) # for columns

# mean also has its own method
print(arr3.mean()) # for all the elements in the array

# standard deviation also has similar functionality
print(arr3.std())

15
[3 5 7]
[ 3 12]
2.5
1.707825127659933


In [38]:
# some functions take array obejcts as inputs
print(np.sin(arr4))
print(np.median(arr4))
print(np.exp(arr4))
# there are several functions like sine, cos, tan, etc....

[[-0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849]
 [-0.54402111 -0.99999021]]
8.5
[[  403.42879349  1096.63315843]
 [ 2980.95798704  8103.08392758]
 [22026.46579481 59874.1417152 ]]
