In [2]:
import numpy as np

In [4]:
# Scenario 1
a1 = np.arange(8).reshape(2, 4)
a2 = np.arange(8, 16).reshape(2, 4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [6]:
# when we have same dimensions
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
# Scenario 2
a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)

print(a3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [11]:
# when we have different dimensions - still the addition happens
a3 + a4
# The smaller dimension gets broadcasted to all the rows for array two

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [12]:
# broadcasting can happen in many cases
# (x,y) and (x,y) => yes
# (1,y) and (z,y) => yes
# (1,y) and (x,1) => yes - matrix multiplication
# (1,1) and (x,y) => yes - scalar multiplication