In [26]:
import numpy as np

### Creating Arrays using NumPy

In [5]:
# Creating NumPy arrays
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# For creating 2D arrays
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [14]:
# Creating a zero array - initialize arrays with zeroes and ones
arr3 = np.zeros((2,3))
print(arr3)
# this takes a tuple input and creates an array with the some dimensions
print()
arr4 = np.ones((2,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# creating a identity matrix as an array
arr5 = np.identity(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# You can use most of the basic list comprehensions while creatind an array
arr6 = np.arange(10)
arr7 = np.arange(5, 16, 2) # same as the (start, end, step) in the range funciton
print(arr6)
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[ 5  7  9 11 13 15]


In [24]:
# you can get N- equally spaced floating numbers within any interval
arr8 = np.linspace(5, 20, 10) # this will return 10 equally spaced numbers within the range 5 to 20
print(arr8)

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


In [27]:
# easily copy any numpy array since arr1 = arr2 doesnt work
arr9 = arr8.copy()
print(arr9)

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


### Array Attributes

In [30]:
# .shape method returns the shape of the matrix
arr2.shape

(2, 3)

In [34]:
arr9 = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(arr9) # these are two matrixes stacked parallel to each other
print(arr9.shape) # this would be a 3D array

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [37]:
# you can tell the Dimensionality directly
arr9.ndim

3

In [39]:
# you can tell the size = no of items using
arr9.size

8

In [42]:
# similarly the memory size of the element inside the array can be known using
arr9.itemsize
# itegers - 4
# Float - 8

4

In [44]:
# for a text output
arr9.dtype

dtype('int32')

In [47]:
# you can convert the datatype of the elements inside an array using
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

### Indexing, Slicing and Iteration

In [51]:
# You can directly reshape an array
arr10 = np.arange(24).reshape(3,8)
print(arr10)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [54]:
# indexing on 2D arrays works similar to indexing in lists
arr10[1]
# this will return the row with index 1

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
arr10[:,3]
# if you print all the 3rd elements in all the rows - you get 3rd column

array([ 3, 11, 19])

In [59]:
arr10[1:, 3:5]
# will print 2nd rows and 3 to 5 columns

array([[11, 12],
       [19, 20]])

In [61]:
# general iteration is different for arrays
for i in arr10:
    print(i)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


In [62]:
# if you want to iter every element
for i in np.nditer(arr10):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
